language: node_js
node_js:
  - "12"
  - node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:yarn test:coverage && :yarn coveralls && rm -rf ./coverage